language: node_js

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  - PATH=$PATH:$HOME/.meteor
  # Download Meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
  - meteor npm install

script:
    # Quick fix https://github.com/studiointeract/accounts-ui/pull/111
  - mkdir packages
  - cd packages
  - git clone https://github.com/jLouzado/accounts-ui
  - cd ..
    # Run all tests:  Unit test & Integration test
  - meteor npm run coverage
    # Save coverage now
  - cat .coverage/lcov.info | ./node_modules/.bin/codecov || true # ignore coveralls error
